examples/61will.space_dev/inventory/openshift-ansible/telemetry.inventory, patches/components.yml.patch, playbooks/sa-telemetry/private/config.yml, scripts/bootstrap.sh, scripts/demo_setup.sh
Allow installation of telemetry-framework on OpenShift 3.10. I'm merging this against a new branch `devel` so that `master` doesn't substantially change right now.
=> Allow installation of SA-Telemetry on OpenShift 3.10

roles/sa_telemetry_consumers/templates/metrics-consumer-deployment.yaml.j2
This passes the uname argument for the metrics consumer so that the consumer
is loading with a unique name in k8s.
=> Pass uname arg to metrics consumer

scripts/bootstrap.sh
The current _TOPDIR=`pwd` directive makes the bootscript fail when it's not running on a specific path telemetry-framework.
The proposal makes the script work no matter where the script is run.
=> Set _TOPDIR on the bootstrap script correctly

deploy/roles/deploy.builder/templates/service-assurance/alertmanager/alertmanager.yaml
Without this Alertmanager pod just sits in pending state due to FailedScheduling
=> Drop nodeSelector from alertmanager roles

tests/README.md, tests/minimal-collectd.conf, tests/smoketest.sh, tests/smoketest_entrypoint.sh, tests/smoketest_job.yaml
* Runs collectd w/ amqp1 plugin inside the saf-telemetry namespace in the cluster
* Collects CPU metrics and pushes it to the bus
* Checks for those CPU metrics (okay, ANY cpu data at the moment) in prometheus
* This validates the qdr router, smart gateway, and prometheus typically in under 10s
=> Initial smoke test idea

deploy/import-downstream.sh
Use a specific container image version tag for the Smart Gateway and Smart
Gateway Operator in order to avoid using the 'latest' container image tag.
=> Use specific container images for SGO and SG

.travis.yml, deploy/deploy.sh, deploy/quickstart.sh
* Re-added wait for prometheus-operator to cut down on CRD wait spam
```
[csibbitt@laptop deploy (csibbitt-594-downstream-tests) ]$ ./quickstart.sh --downstream-secret=~/6340056-cloudops-pull-secret.yaml 
[...]
Importing containers from downstream
secret/6340056-cloudops-pull-secret created
[...]
Docker Image:   registry.redhat.io/openshift3/prometheus@sha256:b0df6a353ecc3b210710151ef370b241c55912b3b3bd21ac98fc6418b4708d01
[...]
[csibbitt@laptop tests (csibbitt-594-downstream-tests) ]$ ./smoketest.sh 
[...]
*** [SUCCESS] Smoke test job completed successfully
```
Travis tested the other case
=> Quickstart supports downstream

deploy/service-assurance/prometheus/prometheus.yaml
This is compatible with the current smart-gateway-operator master branch: https://github.com/redhat-service-assurance/smart-gateway-operator/blob/master/roles/smartgateway/tasks/main.yml#L81
=> Change label `smartgateway: white` to `app: smart-gateway`

deploy/import-downstream.sh, deploy/import-upstream.sh, deploy/operators/prometheus/clusterrole.yaml, deploy/operators/prometheus/clusterrolebinding.yaml, deploy/roles/deploy.builder/defaults/main.yml, deploy/roles/deploy.builder/tasks/main.yml, deploy/roles/deploy.builder/templates/operators/prometheus/operator.yaml, deploy/roles/deploy.builder/templates/service-assurance/prometheus/prometheus.yaml, tests/install-and-run-ocp.sh
These changes are related to work done to deploy SAF into an
environment where OpenShift Monitoring has been deployed. The current
way prior to this change would result in overlapping namespaces for
the ClusterRole and ClusterRoleBinding.
Additionally, Prometheus Operator has been setup to be namespace
bound, and will not act on requests for Prometheus objects that
haven't been created in this namespace.
A new parameter has been added (defaulted to existing 20G sizing) of
the PVC request by Prometheus. Allows for using smaller or larger PVC
requests now.
Downstream and upstream versions have been updated to reflect the new
method that allows us to use a different tag name from that of the
version which makes the tagging slightly less confusing.
Removed the static prometheus.yaml since it …
=> Allow for SAF to coexist with openshift-monitoring

deploy/README.md, deploy/roles/deploy.builder/templates/operators/smartgateway/operator.yaml
While verifying the end state of the labels I discovered that I recently broke
the internal operator-sdk framework metrics for the SGO. I noticed there is a
service called `smart-gateway-operator-metrics` that wants to lead you to port
8383 of the operator where you'll find metrics about the operator itself like
`ansible_operator_reconciles` and `controller_runtime_reconcile_time_seconds` as
well as golang internals, REST stats, and work queue stats. Neat!
That functionality depends on having that `name:` label, however much I might
hate it.
See: https://github.com/operator-framework/operator-sdk/blob/1ee9386dc2c4d910a2b8e673561214740b07a7f2/pkg/metrics/metrics.go#L109
So this patch adds it back and updates the documentation to reflect the end
state.
Before this change:
```
$ oc describe …
```
=> Cleanup label docs and fix SGO metrics

tests/performance-test/Dockerfile, tests/performance-test/deploy/README.md, tests/performance-test/deploy/config/.gitignore, tests/performance-test/deploy/config/hosts.json, tests/performance-test/deploy/scripts/performance-test-entrypoint.sh, tests/performance-test/main.go
* Docker build fixes
* Got "dest dir must end with a /" error on line 3
* Copying of Grafana key didn't work (no instructions to get the key)
* Fixed entrypoint script to get grafana api key working
* Existing version gave:
`/performance-test/exec/performance-test-entrypoint.sh: line 18:
/performance-test/grafana/apikey: Permission denied`
* New version uses /tmp directory
* Fixed job and pod names in tests/performance-test/deploy/README.md
* Just a doc bug
* Also fixed whitespace in line endings
* Added a gitignore for the hosts config
* Removed the existing file because it gets generated at runtime
=> Changes required to get this working in my env

deploy/import-downstream.sh
Bump the version of SG to import for downstream due to an errata being
released to account for latest CVEs in RHEL base image. No other functionality
has been changed other than bumping the base image.
https://access.redhat.com/errata/RHBA-2019:2684
=> Bump the SG version for latest errata

tests/performance-test/Dockerfile, tests/performance-test/README.md, tests/performance-test/deploy/README.md, tests/performance-test/deploy/grafana-launcher.sh, tests/performance-test/deploy/performance-test-job.yml, tests/performance-test/deploy/scripts/launch-test.sh, tests/performance-test/docker-push.sh, tests/performance-test/main.go
While taking a deeper look at this and figuring out what's needed next for robust multi-cloud testing I noted a few minor annoyances (including possibly a fatal bug with the "-d" option to collectd-tg?) that I cleaned up along the way.
I ran this and got metrics like `sa_collectd_plugin018_gauge{endpoint="prom-http",exported_instance="host0779",plugin018="ti2137288709",service="cloud1-smartgateway",type="base"}` in my prometheus.
=> Various improvements to the perftest stuff

tests/performance-test/deploy/config/test-configs.yml, tests/performance-test/deploy/performance-test-job.yml.template, tests/performance-test/deploy/performance-test.sh, tests/performance-test/grafana/perftest-dashboard.json, tests/performance-test/grafana/prom-servicemonitor.yml, tests/performance-test/grafana/prom2-dashboard.json, tests/performance-test/grafana/qdr-servicemonitor.yml
* templated job to be minishift/quicklab agnostic
* added additional service monitors
* prometheus
* qdr
* added two dashboards
* default prometheus-specific monitoring board
* custom SAF perf monitoring board
=> Adding grafana dashboard - no automation yet

docs/README.adoc
Having the `quickstart.sh` script mentioned in the docs is a little misleading because, unlike what the docs say, it does not take care of all of the steps necessary to launch SAF upstream version. Some of the pre-requisites to running `quickstart.sh` are mentioned later in the docs, causing confusion for the first time viewer. In addition, it is quite simple to quickly launch SAF for development without the script, making it unnecessary.
I also added some additional logic to properly multiplex the 'downstream' and 'upstream' terms.
=> Adjusted docs for upstream SAF installation

deploy/quickstart.sh
Having this option would make it more obvious when something has gone wrong. @pleimer  's recent issue with not having ansible installed would now result in an immediate exit from the script with this as the last console message:
```
./quickstart.sh: line 39: ansible-playbook: command not found
```
Letting Travis test this for me.
=> Add set -e to quickstart

tests/performance-test/dashboard.go
Before this fix (during docker build):
```
./dashboard.go:121:7: assignment mismatch: 1 variable but d.client.SetDashboard returns 2 values
./dashboard.go:124:7: assignment mismatch: 1 variable but d.client.SetDashboard returns 2 values
The command '/bin/sh -c go get gopkg.in/yaml.v2 &&     go get github.com/grafana-tools/sdk &&     go build -o main &&     mv main /tmp/' returned a non-zero code: 2
```
Cause is this upstream change: https://github.com/grafana-tools/sdk/pull/33/files#diff-360b9f3ea407e904e28272cb297b43dbR159
After this fix, the golang part of the build succeeds. 
I didn't test any deeper than that (or add proper error handling that outputs the new StatusMessage return value) because I want to throw this code away anyways.
I've actually not been able to fully verify this …
=> Fix perftest build

tests/performance-test/deploy/performance-test-job-tg.yml.template
This removes many of the steps required for building the docker image in the performance test by telling the job to pull a static image in Quay.io. We were having a lot of issues building the images locally and this will allow development to continue without the problems of building every time. This is a temporary solution, but necessary for now
=> Pull performance test image from quay.io instead of from internal registry

deploy/deploy.sh
* During CI tests pods can get stuck on registry related errors
* Usually Unauthorized or Not Found
* These appear to be race conditions with the setup of the ImageStreams
* In each case, deleting the affected pod leads to recovery
* This "fix" adds a 10m timeout to our rollout checks
* After timeout, the relevant pod is killed
* In cases where rollout is proceeding smoothly, this add NO extra delay
* In cases where rollouts are failing, delays in multiples of 10m are possible
* But much higher probability that the rollout will eventually complete
=> Fix(?) spurious smoketest failures

tests/performance-test/Dockerfile
https://github.com/grafana-tools/sdk/pull/38/files says we need 1.13
=> Update to newer golang in perftest container

deploy/quickstart.sh
Reminder that quickstart.sh is not for production use. I don't recommend this approach in general. :)
Still looking for an environment-agnostic way to get the `sysctl` command executed on the labelled node, but that's not for this PR.
=> Small change to quickstart to make it work outside of minishift

tests/smoketest/minimal-collectd.conf.template, tests/smoketest/smoketest_entrypoint.sh
Add functionality to the smoketest_entrypoint.sh that will return the number of
documents created during the test. Testing will return only true if both the
events and metrics smoke tests return without issue.
Updates the collectd minimal configuration for smoke testing to load the
appropriate plugins so that the threshold plugin will result in a bunch of
events being written into an index within ElasticSearch.
=> Add events testing to smoke test

tests/performance-test/deploy/qdrouterd.yaml.template, tests/performance-test/performance-test.sh
Perftest script isn't working for me; noticed this image pull problem in my minishift environment where `docker-registry.default.svc` doesn't work so templated it like various other places we refer to the registry.
I'm l running into a problem with the OCPPrometheus datasource, so the perftest stuff is still broken for me, but this definitely helps.
=> Templated qdr registry URL in perftest

tests/performance-test/performance-test.sh
* This could never have worked AFAICT?
* String comes back from `oc get secret` as a multi-line string
* sed can not pattern match across multiple lines
* Use bash search/replace expansion to remove newlines before
handing off to sed
=> Fixed OCPPrometheus datasource addition in perftest

tests/performance-test/deploy/qdrouterd.yaml
Paul had this right initially in the PR. This shorter prefix is simpler, more flexible, and more closely matches what the client side uses for real. See: https://github.com/openstack/tripleo-heat-templates/commit/13ffaf688ecabb02378e8ef31107ae2be7fd1010
=> Simplified collectd prefix in qdr config

tests/infrared/infrared-openstack.sh
* Updated OSP_BUILD and VM_IMAGE defaults to 7.7-latest and rhel-7.7.
* Added NTP_SERVER param to the script.
=> Update build versions in infrared script

tests/performance-test/performance-test.sh
$   ./performance-test.sh -t tb -c 600 -h 5 -p 1000 -i 1 -n 4
[...]
*** Deploying Edge Router ***
sed: can't read ./deploy/qdrouterd.yaml: No such file or directory
*  Code could never have worked, filename is wrong
Still having trouble with the dashboards not loading, but this got me past the QDR hurdle.
=> Fix perftest QDR not deploying

tests/performance-test/performance-test.sh
You don't know how lucky you are growing up in an era of fast floating point arithmetic! :smile: Shifting the decimal like this is a good tool to have in your pocket.
The test rig I've been using for perf testing didn't have `bc` installed. No biggie, but figured we could skip a `yum install` of this in our future automation. We should aggressively limit dependencies until all of this is containerized (if ever).
=> Eliminate 'bc' dependency from perftest script

tests/performance-test/deploy/performance-test-job-tb.yml.template, tests/performance-test/grafana/perftest-dashboard.json, tests/performance-test/grafana/qdr-servicemonitor.yml, tests/performance-test/performance-test.sh
I also put in an events latency panel as a place holder, but it does not actually work yet. Feel free to make some layout recommendations you may think look better.
Edge router results work with all currently implemented alarms. Separate qdr-test metrics are graphed in the 'QDR' row of the dashboard (not shown below). This is a fairly un-intrusive update and will work even if the test is run with metrics sent directly to qdr-white.
**Dashboard View**
=> Edge router monitoring added to the perftest dashboard

tests/infrared/metrics-collectd-qdr.yaml.template
The fs_info extra_stats doesn't appear to work in the OSP deployment described by this automation. Collectd log shows:
```
[2019-11-12 21:31:30] virt plugin: virDomainGetFSInfo failed: -1
[2019-11-12 21:31:30] virt: Failed to get file system info
```
The plugin outputs no metrics.
After removing fs_info, the plugin started generating metrics, but also it seems the domain_state stat generates spam:
```
[2019-11-13 19:43:10] Notification: severity = OKAY, host = compute-0.localdomain:2066b66a-70c0-47d7-911a-7e8de613614d, plugin = virt, type = domain_state, message = Domain state: the domain is running. Reason: returned from paused state
[2019-11-13 19:43:11] Notification: severity = OKAY, host = compute-0.localdomain:2066b66a-70c0-47d7-911a-7e8de613614d, plugin = virt, type = domain_state, …
```
=> Trimming extra_stats list in infrared test harness

tests/infrared/metrics-collectd-qdr.yaml.template
* Setting these as reasonable defaults for integration testing
* Note the change from CollectdExtraPlugins to CollectdDefaultPlugins
* This effectively overrides this list: https://github.com/openstack/tripleo-heat-templates/blob/master/deployment/metrics/collectd-container-puppet.yaml#L80
* Adds: intel_rdt, ipmi, memory, ovs_events, ovs_stats
* Removes: tcpconns
* This config produces <100 metrics/s/node
* Down from ~1000 with the previous version of this file
* Allows us the possibility of meeting the 100 nodes/cloud requirement
* \# of VMs and network interfaces have the largest impact in production
* I wanted to explicitly set the interval of every plugin
* Found that collectd::plugin::ovs_stats::interval does not work/exist
* Adjusted overall interval to 5s as that's the lowest we …
=> New supportable defaults for integration testing

.travis.yml
Only enable our CI testing for changes going into the saf-ocp3 branch. Currently
required since we don't have access to an upstream OKD 4 instance that works via
the traditional 'oc cluster up' method. Only instantiation of clusters into AWS
is currently supported.
=> Only enable CI testing for OCP3

tests/performance-test/grafana/perftest-dashboard.json
Awhile ago[1], I started to notice an error occasionally on the dashboard elements that count all the metrics in prometheus: "vector cannot contain metrics with the same labelset". It comes from the count_over_time() call, which takes a result set like this:
```
scrape_duration_seconds{endpoint="prom-http",instance="10.128.1.243:8081",job="saf-default-telemetry-smartgateway",namespace="sa-telemetry",pod="saf-default-telemetry-smartgateway-2-nss5q",service="saf-default-telemetry-smartgateway"}	0.001409569 @1576253970.625
0.001131969 @1576253971.625
scrape_duration_seconds{endpoint="prom-http",instance="10.128.1.244:8081",job="saf-default-telemetry-smartgateway",namespace="sa-telemetry",pod="saf-default-telemetry-smartgateway-2-n24sv",service="saf-default-telemetry-smartgateway"} …
```
=> Update perftest dashboard to new pod names

deploy/quickstart.sh
We changed the name and path of the application and container registries in order
to avoid named registries. This change updates the quickstart.sh to account for this
change so that a Service Assurance deployment results.
Name of the Subscription has been updated to reflect the pattern that OLM created
for other dependent Subscriptions of the SAO. Updated spec.name to account for the
new package name.
=> Update quickstart.sh for new application registry

deploy/quickstart.sh
You need to use the ES workaround version for it to work anyways: https://github.com/redhat-service-assurance/telemetry-framework/blob/master/deploy/quickstart_ESworkaround.sh
This also matches the defaults in the SAO: https://github.com/redhat-service-assurance/service-assurance-operator/blob/49e11e5242cfe1debe42da352f12c50659dd4dd9/roles/serviceassurance/defaults/main.yml#L4
=> Disable events in main quickstart
